import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import ProviderComp from '../redux/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Redux Toolkit with Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderComp>
          <Navbar />
          {children}
        </ProviderComp>
      </body>
    </html>
  )
}
